### PR TITLE
Updating highstock version

### PR DESCRIPTION
**Pull request by ayelen**

### CODE REVIEW

**Comment by ayelen** [comment]
@golyakov Could you create a new npm version once merged?

**Comment by golyakov** [comment]
@ayelen Please use the link on the git repository instead npm

**Comment by ayelen** [comment]
@golyakov thanks for the merge, but we really need this on NPM to avoid any new change that could add messing or unnecessary things to a project on production. Please let me know once published or if you need help, and thanks for the support!

**Comment by golyakov** [comment]
@ayelen Package updated

**Pull request merged**
